
name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:


jobs:
  test-ubuntu:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: dart --version
      - run: flutter --version
      - run: flutter test

  test-windows:
    name: Test on windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: dart --version
      - run: flutter --version
      - run: flutter test

  test-macos:
    name: Test on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: dart --version
      - run: flutter --version
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    needs: test-macos
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - name: Upload iPA
        uses: actions/upload-artifact@master
        with:
          name: ios-build
          path: build/ios

  build_apk:
    name: Build Flutter (Android)
    needs: test-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - run: flutter pub get
#     - run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
#     - run: flutter build appbundle --target-platform android-arm,android-arm64
    - run: flutter build appbundle
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/apk/release
    - name: Upload App Blundle
      uses: actions/upload-artifact@master
      with:
        name: app-bundle-build
        path: build/app/outputs/bundle/release

  build_win:
    name: Build Flutter (win)
    runs-on: windows-latest
    needs: test-windows
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - name: Upload WIN
        uses: actions/upload-artifact@master
        with:
          name: win-build
          path: build/windows/runner/Release
